server:
  port: 8080

spring:
  application:
    name: news-service
  cloud:
    consul:
      host: localhost
      port: 8500    
      discovery:
        healthCheckInterval: 30s
      config:
        enabled: true
  data:
    mongodb:
      host: localhost 
      port: 27017
      database: newsdb
      username: test
      password: password
