server:
  port: 8081

spring:
  application:
    name: news
  cloud:
    consul:
      host: localhost
      port: 8500    
      discovery:
        healthCheckInterval: 30s
      config:
        enabled: true
  data:
    mongodb:
      host: localhost 
      port: 27017
      database: newsdb
      username: test
      password: password

app:
  logging:
    cxf:
      request:
        enabled: true

endpoints:
  health:
    enabled: true
